#!/bin/sh
# Generate metamath.pdf from source file metamath.tex.

# Stop processing if error occurs (-e) and show what we're doing (-x)
set -ex

# Run pdflatex on $1.
# TODO: Add -output-directory _build
do_pdflatex () {
  pdflatex -halt-on-error -interaction=nonstopmode "$1"
}

rm -f realref.sty metamath.bib
touch metamath.ind

do_pdflatex metamath
do_pdflatex metamath
bibtex metamath
makeindex metamath
do_pdflatex metamath
do_pdflatex metamath
